### PR TITLE
Antiswear

### PR DESCRIPTION
**Pull request by Code-Sploit**
This adds an antiswear mod.

To add new badwords edit the file in your world directory named `badwords.txt`.
You have to write the word directly after it without a space or newline.

If you want to use this mod then follow these instructions or it will not work.

### CODE REVIEW

**Comment by BrownHedgehog78** [comment]
@Code-Sploit It adds "whitelist", too?

**Comment by Code-Sploit** [comment]
Bruh i thought i excluded that with a different branch.

**Comment by Code-Sploit** [comment]
But anyways you can merge it together :).

**Comment by BrownHedgehog78** [comment]
This is a duplicate of #48? You can close it

**Comment by Code-Sploit** [comment]
Ye i will!

**Comment by BrownHedgehog78** [comment]
This PR will be not merged, when sometimes you want to say a word and it thinks you say the bad word.

**Pull request closed without merging**
