### PR TITLE
Adds colored hotbar

### PR DESCRIPTION
**Pull request by Anthony-De**

### CODE REVIEW

**Comment by DiamondPlane** [comment]
I'm going to test it now.

**Comment by BrownHedgehog78** [comment]
@Anthony-De Is it WIP?

**Comment by Anthony-De** [comment]
@DiamondPlane Yes, at Elvis26's request.

**Comment by BrownHedgehog78** [comment]
Ok

**Comment by moreavy** [comment]
The colored hotbars disable texture packs, If you have a texture pack that changes the hotbar, it won't work in the server.

**Comment by BrownHedgehog78** [comment]
@Anthony-De Check the teams, here no red.

**Comment by BrownHedgehog78** [comment]
The textures need to be edited.

**Comment by Anthony-De** [comment]
@DiamondPlane
I have made the texture changes that you asked for.

**Comment by BrownHedgehog78** [comment]
> @DiamondPlane
> I have made the texture changes that you asked for.

Nice, it looks good now.

**Pull request merged**
